### ISSUE TITLE
Error on orbit:cache command

### ISSUE THREAD

**Issue by happytodev** [ryangjchandler/orbit#141]
When I launched the command, I have this error : 

```bash
Symfony\Component\ErrorHandler\Error\FatalError

Cannot declare class HappyToDev\Typhoon\App\Providers\RepositoryServiceProvider, because the name is already in use
```

![image](https://user-images.githubusercontent.com/425998/184101479-eeb1bd2e-10b2-42ed-b120-17c12a757e26.png)

**Comment by ryangjchandler** [comment]
@happytodev I'm not sure this is an error in the command since the code is related to your app code, not Orbit.

**Comment by happytodev** [comment]
@ryangjchandler I'm afraid not. I launch this command on a clean install of Laravel + `composer require ryangjchandler/orbit`  and I have exactly the same.

After searching a little this morning, the function `findOrbitModels()` in `CacheCommand.php` seems to catch every class not only the Models class. I think this is not the expected behaviour, but perhaps I'm wrong. I just try to understand.

**Comment by markvaneijk** [comment]
I'm also having this error in a new Laravel project (v9.x)

**Comment by ryangjchandler** [comment]
Should be fixed in latest release. Sorry for delay!

**Comment by markvaneijk** [comment]
Awesome @ryangjchandler

**Comment by happytodev** [comment]
Sorry Ryan (@ryangjchandler), but this error still after the update. 

I ran :

`composer update`

and

`php artisan optimize:clear` 

Do you have another idea ?

**Comment by markvaneijk** [comment]
For what it's worth, for me it did solve the error.

**Comment by happytodev** [comment]
> For what it's worth, for me it did solve the error.

Do you have do something particular ? For me the error stills :-(

**Comment by markvaneijk** [comment]
I only updated the package using composer @happytodev
